= Конспект
https://github.com/winter-yuki/Diary

== Команда

- Андрей Стоян (тимлид)
- Григорий Райкин (разработчик)
- Артём Горбачев (разработчик)

== Описание

Существует множество приложений для заметок и ведения конспектов.
Но все они ничем концептуально не отличаются от карандаша и тетрадки:
фиксированный размер страниц, сложно вставить запись в середину текста,
исходный материал обычно находится в pdf'ках и удобно сослаться на него невозможно,
приходится кучу всего переписывать вручную.

.Конспект - это индивидуально организованные в сжатой форме материалы и мысли
- Индивидуально - все думают и воспринимают по-разному, способ конспектирования должен быть сколь угодно гибким
- Организованные - конспект имеет структуру и она важна (не должна ломаться от дописываний и комментариев), на нее должно быть можно “посмотреть с высоты птичьего полета”
- Сжатой форме - невозможно восстановить в полноте источник, нужна ссылка с возможностью быстрого перехода
- Материалы - эта информация уже где-то есть: переписывать условия и доказательства теорем - глупое занятие и мешает воспринимать лекцию
- Мысли - хаотичная, плохо организованная информация, имеет огромное количество ассоциативных связей, которые постоянно добавляются и дополняются

Решение -- организовать конспект как ячейки в jupiter notebook с атомарными тезисами,
каждая имеет свой тип ввода: язык разметки, рисунок.
Ячейки связаны друг с другом ссылками, по которым генерируются оглавления и майнд-карты.

.На конспект можно смотреть как на кодовую базу:
- Система контроля версий и форки
- Статический анализ конспекта и генерация: карты связей, флеш-карточки для повторения

.Преподаватель генерирует слайды из своего референсного конспекта
- Пока листаются слайды, студентам открываются новые части конспекта
- Студент по мере осознания таскает к себе блоки информации, преобразуя под себя

== План реализации

.Минимум
. Экран с ячеками вида:
.. Текстовые
.. Canvas для рисования
. Переход по ссылке на место в pdf (специальный кликабельный элемент на канвасе)
. Сохранение конспекта на диск (файлы с текстом и канвасами (a la xopp формат) в зип архиве)
. Отображение двух конспектов, копирование ячеек из одного в другой
