= Конспект

== Проблема ==

.Конспект -- это индивидуально организованные в сжатой форме материалы и мысли:
- "индивидуально" -- все думают и воспринимают по-разному, способ конспектирования должен быть сколь угодно гибким;
- "организованные" -- конспект имеет структуру и она важна (не должна ломаться от дописываний и комментариев), должна быть возможность “посмотреть с высоты птичьего полета”;
- "сжатой форме" -- невозможно восстановить в полноте источник, нужна ссылка с возможностью быстрого перехода;
- "материалы" -- эта информация уже где-то есть: переписывать условия и доказательства теорем - бесполезное занятие и мешает воспринимать лекцию;
- "мысли" -- хаотичная, плохо организованная информация, имеет огромное количество ассоциативных связей, которые постоянно добавляются и дополняются.

Существует множество приложений для заметок и ведения конспектов, но по описанным критериям они не так далеко ушли от карандаша и тетрадки.
Если приложение заточено под рукописный ввод, то там скорее всего фиксированный размер страниц, нет хорошей системы ссылок и оглавлений.
Если приложение подразумевает ввод с помощью какого-то языка разметки, то там обычно не предусмотрен рукописный ввод.
А главное -- нигде нет развитой работы с источниками, PDF документ учебника или презентации не становятся частью конспекта, нельзя сослаться на конкретное место в нём.
Но в этом же и суть конспектирования -- упорядочение и преобразование уже имеющихся материалов.

== Решение ==

Конспект организуется как набор ячеек, a la jupyter notebook, содержащих атомарные высказывания.
Это даёт гибкость: ячейки можно переупорядочивать и добавлять в произвольное место конспекта.
Размер ячейки соответствует содержимому, но оставляется небольшим.
Каждая ячейка имеет свой тип ввода: язык разметки, рукописный ввод, исполнимый код...

Ячейкам и конспектам можно присваивать идентификаторы, чтобы ссылаться на них из других ячеек и конспектов.
Ссылаться так же можно на страницу и рисунок в PDF документе.
Документ открывается в самом приложении и копируется в файл с конспектом, чтобы быть всегда доступным.

=== Notes as a code: среда разработки знаний ===

.На множество конспектов можно смотреть как на кодовую базу, эта аналогия оказывается продуктивной:
- Различные конспекты соответствуют различным модулям, иерархически организованным в пакеты;
- Ячейки с идентификаторами -- функции, на которые можно сослаться (вызвать), по ссылкам можно переходить, как к определениям в IDE;
- По конспекту можно проводить своего рода статический анализ, который позволяет сгенерировать карты связей и флеш-карточки для повторения перед экзаменом;
- И наконец, конспекты можно версионировать, форкать и смотреть diff.

=== Применение ===

.Попробуем представить, как с помощью этих возможностей может проходить курс:
- Преподаватель делает референсный конспект курса:
    * Содержит полный набор сведений, изучаемых в курсе;
    * Поскольку курс - всегда выжимка, конспект содержит ссылки на источники;
- Студенты делают "ленивые форки" референсного конспекта;
- По референсному конспекту составляются слайды лекций, которые автоматически связываются с конспектом:
    * В течение лекции, студентам становятся доступны новые части конспекта (если преподаватель не любит заранее показывать материал);
    * По мере прохождения и освоения, студенты перетаскивают к себе в форки всё новые ячейки из референсного, дополняя их рисунками, комментариями и ссылками на источники, где может быть объяснено понятнее;
    * Образуется чёткая связь: ячейка есть в форке -- её содержимое понятно;
- Студенты могут шарить конспекты друг другу и преподавателю:
    * Чтобы смотреть лучшие объяснения и материалы друг у друга;
    * Преподаватель, анализируя как изменился его конспект в форках, получает лучший конструктивный фидбек по улучшению курса.

Преподаватель может не делать референсный конспект, им может стать один из конспектов студентов и пойти по пути эволюции.

Такой подход позволяет избавить лекции от записывания всего, что говорит преподаватель, и сосредоточиться на понимании материала и задавании вопросов.

=== Diary ===

Мысли и идеи не так уж бессмертны как может показаться.
По большей части они разбросаны по специализированной литературе, по полям книг из библиотеки автора.
Исследователи собирают эти знания и порождают не менее специальную литературу, часто недоступную обычным читателям.

Но представьте, что вы читаете книгу, на полях которой делал пометки Пастернак.
Или что вдруг из пожелтевших страниц выпало письмо, в котором Аркадий Стругацкий развивает идею, о которой вы сейчас прочитаете.

Идеи можно сделать доступнее.
Развернём ссылки: теперь они из документов указывают на записи других людей.
Так, читая книгу или статью, можно видеть, что подумал интересный вам человек, когда читал то же самое.

Артефакты науки и искусства становятся точками синхронизации мыслей людей, живущих сейчас и живших когда-то.
